- name: Dcokerのインストールに必要なパッケージをインストール
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest

- name: DockerリポジトリのGPGキーを追加
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Dockerリポジトリをapt source に追加
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Dockerをインストール
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    
  notify: 
    - "dockerグループにユーザを追加"
    - "dockerデーモンをリセット"